# Generated by Django 3.2.25 on 2024-11-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_has_sizes_product_has_dietary_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='dietary_options',
            field=models.ManyToManyField(blank=True, to='products.DietaryOption'),
        ),
    ]
