# Generated by Django 3.2.25 on 2024-11-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20241102_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_sizes',
            new_name='has_options',
        ),
    ]
